### ISSUE TITLE
Fetching HN data makes Sycamore seem sluggish

### ISSUE THREAD

**Issue by awulkan** [sycamore-rs/hackernews-sycamore#2]
At first I was very disappointed at how sluggish Sycamore appeared to be. It took 10+ seconds to open a page with many comments. Then I inspected the networking tab and saw that it was actually the fetching of data (610 requests) that took a long time, not Sycamore itself. I think the demo would be much more appealing if data was fetched and added in an async manner.

Just my 2 cents. Good luck with the project, it looks cool! :)

**Comment by lukechu10** [comment]
Hello there. Sorry for not having responded but I was wondering why you closed this issue? This seems like a valid suggestion for this demo app.

**Comment by awulkan** [comment]
Hey, no worries. Feel free to reopen the issue if you want to.

I went through my list of open issues and closed the ones that I felt weren't leading anywhere. I assumed that no one cared about this issue.
